version: '3.8'

services:
  frontend:
    image: szgody/homephotosvideos:frontend-1.0
    depends_on:
      - backend
    restart: unless-stopped

  backend:
    image: szgody/homephotosvideos:backend-1.0
    environment:
      - NODE_ENV=production
      - PORT=3000
      - DATA_DIR=/app/data
      - PUBLIC_DIR=/app/public
      - BASE_URL=
      - PHOTOS_PATH=/photos
      - VIDEO_THUMBNAILS_PATH=/video_thumbnails
      - PHOTO_THUMBNAILS_PATH=/photo_thumbnails
      - VIDEOS_PATH=/videos
      # CORS 配置
      - ALLOWED_ORIGINS=http://localhost:8080,*
      - ORIGINAL_VIDEOS_PATH=/app/public/original/videos
      - ORIGINAL_IMAGES_PATH=/app/public/original/images
    volumes:
      - ./data:/app/data
      - ./public:/app/public
    restart: unless-stopped

  nginx:
    image: szgody/homephotosvideos:nginx-1.0
    ports:
      - "8080:80"  
    depends_on:
      - frontend
      - backend
    restart: unless-stopped

volumes:
  backend_public:
