# 照片和视频管理系统 Docker Compose 配置
version: '3'

services:
  # 后端服务配置
  backend:
    image: home-photos-backend:latest  # 使用最新的后端镜像
    ports:
      - "3001:3000"  # 将容器3000端口映射到主机3001端口
    volumes:
      # 数据存储映射 - 可根据需要修改主机路径（冒号左侧）
      - /path/to/your/data:/app/data            # 存储缩略图和处理后的照片
      - /path/to/your/public:/app/public        # 存储原始上传文件
    environment:
      # 应用环境配置
      - NODE_ENV=production                     # 生产环境
      - PORT=3000                               # 应用内部端口
      - DATA_DIR=/app/data                      # 数据存储位置
      - PUBLIC_DIR=/app/public                  # 公共文件存储位置
      - BASE_URL=http://localhost:8080          # 前端访问地址，修改为您的IP或域名
      - PHOTOS_PATH=/photos                     # 照片访问路径
      - THUMBNAILS_PATH=/photo_thumbnails       # 缩略图访问路径
      - VIDEOS_PATH=/videos                     # 视频访问路径
      - VIDEO_THUMBNAILS_PATH=/video_thumbnails # 视频缩略图访问路径
      - ALLOWED_ORIGINS=http://localhost:8080,http://nginx,http://localhost  # 允许的跨域来源
    networks:
      - app-network
    restart: unless-stopped                     # 自动重启策略

  # 前端Nginx服务配置
  nginx:
    image: nginx:1.21                          # Nginx镜像版本
    ports:
      - "8080:80"                              # 将Nginx端口映射到主机8080端口
    volumes:
      # 前端文件和配置映射
      - ./dist:/usr/share/nginx/html:ro        # 前端静态文件(只读)
      - ./docker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf:ro  # Nginx配置(只读)
      # 缩略图和视频缩略图文件映射，以便Nginx可以直接提供服务
      - /path/to/your/data/photo_thumbnails:/app/data/photo_thumbnails
      - /path/to/your/data/video_thumbnails:/app/data/video_thumbnails
    networks:
      - app-network
    depends_on:
      - backend                                # 依赖后端服务先启动
    restart: unless-stopped                    # 自动重启策略

# 网络配置
networks:
  app-network:
    driver: bridge                             # 使用桥接网络